#!/bin/bash
> progress

declare -a StringArray=("lu_cb")

for filename in "${StringArray[@]}"  ;do 
   echo $filename "is in progress"
   echo $filename "is in progress" >> progress
   ../build/X86_cw/gem5.opt -d ../m5out/cwres3/$filename/w_10 ../configs/example/se.py --num-cpus=16 --num-dir=16 --cpu-type=TimingSimpleCPU --cpu-clock=2GHz --caches --l1d_size=16kB --l1i_size=16kB --mem-type=SimpleMemory --cw-bits=10 --mem-size=4GB --ruby --topology=Mesh_XY --mesh-rows=4 --network=garnet2.0 -c ../benchmark/splash-parsec/$filename -o "-p 1"
   echo "10" >> progress
   ../build/X86_cw/gem5.opt -d ../m5out/cwres3/$filename/w_12 ../configs/example/se.py --num-cpus=16 --num-dir=16 --cpu-type=TimingSimpleCPU --cpu-clock=2GHz --caches --l1d_size=16kB --l1i_size=16kB --mem-type=SimpleMemory --cw-bits=12 --mem-size=4GB --ruby --topology=Mesh_XY --mesh-rows=4 --network=garnet2.0 -c ../benchmark/splash-parsec/$filename -o "-p 1"
   echo "12" >> progress
   for i in {20..32..2}
   do
      ../build/X86_cw/gem5.opt -d ../m5out/cwres3/$filename/w_$i ../configs/example/se.py --num-cpus=16 --num-dir=16 --cpu-type=TimingSimpleCPU --cpu-clock=2GHz --caches --l1d_size=16kB --l1i_size=16kB --mem-type=SimpleMemory --cw-bits=$i --mem-size=4GB --ruby --topology=Mesh_XY --mesh-rows=4 --network=garnet2.0 -c ../benchmark/splash-parsec/$filename -o "-p 1"
      echo $i >> progress
   done

   echo $filename 'done'
   echo $filename "done" >> progress
done







